export const skillsOptions = [
  { id: "Adv-java", name: "Adv-java" },
  { id: "JDBC", name: "JDBC" },
  { id: "AWS", name: "AWS" },
  { id: "Analytical Skills", name: "Analytical Skills" },
  { id: "core", name: "core" },
  { id: "Critical Thinking", name: "Critical Thinking" },
  { id: "MySQL", name: "MySQL" },
  { id: "OOPs", name: "OOPs" },
  { id: "UNIX", name: "UNIX" },
  { id: "GitHub", name: "GitHub" },
  { id: "Programming", name: "Programming" },
  { id: "SQL", name: "SQL" },
  { id: "Machine Learning", name: "Machine Learning" },
  { id: "iOS development", name: "iOS development" },
  { id: "Manual Testing", name: "Manual Testing" },
  { id: "MongoDB", name: "MongoDB" },
  { id: "Android", name: "Android" },
  { id: "C++", name: "C++" },
  { id: "Azure", name: "Azure" },
  { id: "CSS", name: "CSS" },
  { id: "Redis", name: "Redis" },
  { id: "Logical Reasoning", name: "Logical Reasoning" },
  { id: "Docker", name: "Docker" },
  { id: "DBMS", name: "DBMS" },
  { id: "Angular", name: "Angular" },
  { id: "Node", name: "Node" },
  { id: "Flutter", name: "Flutter" },
  { id: "Data structures", name: "Data structures" },
  { id: "Javascript", name: "Javascript" },
  { id: "JSP", name: "JSP" },
  { id: "Algorithms", name: "Algorithms" },
  { id: "JSTL", name: "JSTL" },
  { id: "Servlets", name: "Servlets" },
  { id: "React", name: "React" },
  { id: "Python", name: "Python" },
  { id: "GCP", name: "GCP" },
  { id: "PHP", name: "PHP" },
  { id: "Springs", name: "Springs" },
  { id: "Automation Testing", name: "Automation Testing" },
  { id: "Tomcat", name: "Tomcat" },
  { id: "Operating System", name: "Operating System" },
  { id: "Networking", name: "Networking" },
  { id: "Hibernate", name: "Hibernate" },
  { id: "C", name: "C" },
  { id: "Core java", name: "Core java" },
  { id: "Artificial Intelligence", name: "Artificial Intelligence" },
  { id: "HTML", name: "HTML" },
  { id: "JEE", name: "JEE" },
  { id: "C#", name: "C#" },
  { id: "Data Science", name: "Data Science" },
  { id: "AI - ML", name: "AI - ML" },
  { id: "Linux", name: "Linux" },
];

export const stateList = [
  { id: "Delhi", name: "Delhi" },
  { id: "Manipur", name: "Manipur" },
  { id: "Goa", name: "Goa" },
  { id: "Jammu & Kashmir", name: "Jammu & Kashmir" },
  { id: "Orissa", name: "Orissa" },
  { id: "Lakshadweep", name: "Lakshadweep" },
  { id: "Jharkhand", name: "Jharkhand" },
  { id: "Tamilnadu", name: "Tamilnadu" },
  { id: "Gujarat", name: "Gujarat" },
  { id: "Karnataka", name: "Karnataka" },
  { id: "Andhra Pradesh", name: "Andhra Pradesh" },
  { id: "Nagaland", name: "Nagaland" },
  { id: "Uttar Pradesh", name: "Uttar Pradesh" },
  { id: "Rajsthan", name: "Rajsthan" },
  { id: "Dadra & Nagar Haveli", name: "Dadra & Nagar Haveli" },
  { id: "Bihar", name: "Bihar" },
  { id: "Chhattisgarh", name: "Chhattisgarh" },
  { id: "Daman & Diu", name: "Daman & Diu" },
  { id: "Punjab", name: "Punjab" },
  { id: "Tripura", name: "Tripura" },
  { id: "Maharashtra", name: "Maharashtra" },
  { id: "Assam", name: "Assam" },
  { id: "Haryana", name: "Haryana" },
  { id: "Andaman & Nicobar", name: "Andaman & Nicobar" },
  { id: "Arunachal Pradesh", name: "Arunachal Pradesh" },
  { id: "West Bengal", name: "West Bengal" },
  { id: "Sikkim", name: "Sikkim" },
  { id: "Meghalaya", name: "Meghalaya" },
  { id: "Mizoram", name: "Mizoram" },
  { id: "Telangana", name: "Telangana" },
  { id: "Uttarakhand", name: "Uttarakhand" },
  { id: "Himachal Pradesh", name: "Himachal Pradesh" },
  { id: "Kerala", name: "Kerala" },
  { id: "Madhya Pradesh", name: "Madhya Pradesh" },
  { id: "Pondichery", name: "Pondichery" },
];
